spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/simpleapp
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081